-- Generated by hyprconf2lua v1.0.0
-- https://github.com/yourusername/hyprconf2lua
-- Manual review may be needed for complex directives

---@module 'hl'


local LMB = "mouse:272"

local RMB = "mouse:275"

local down = "j"

local left = "h"

local mainMod = "super"

local menu = "fuzzel"

local opener = "handlr launch"

local right = "l"

local scratchpad = "scratchpad -m fuzzel --dmenu"

local term = "handlr launch x-scheme-handler/terminal --"

local up = "k"

hl.config({
    animations = {
        enabled = true,
    },
})

hl.config({
    decoration = {
        blur = {
            enabled = true,
            passes = 2,
            size = 3,
        },
        rounding = 5,
        active_opacity = 0.96,
        fullscreen_opacity = 0.98,
        inactive_opacity = 0.93,
    },
})

hl.window_rule({
    name  = "opacity_1_0",
    match = {
        class = "^(Hyprlock)$",
    },
    opacity = 1.0,
})

hl.window_rule({
    name  = "noanim",
    match = {
        class = "^(Hyprlock)$",
    },
    no_anim = true,
})

hl.window_rule({
    name  = "nofocus",
    match = {
        class = "^(Hyprlock)$",
    },
    no_focus = true,
})

hl.config({
    dwindle = {
        preserve_split = true,
        pseudotile = true,
    },
})

hl.config({
    general = {
        border_size = 2,
        col.active_border = "rgb(002400)",
        col.inactive_border = "rgb(162016)",
        gaps_in = 5,
        gaps_out = 20,
        layout = "dwindle",
    },
})

hl.config({
    group = {
        groupbar = {
            text_color = "0xffffffff",
        },
        col.border_locked_active = "rgb(003366)",
        col.border_locked_inactive = "rgb(242424)",
    },
})

hl.config({
    misc = {
        disable_hyprland_logo = true,
        disable_splash_rendering = true,
        enable_swallow = true,
        swallow_regex = "^(org.wezfurlong.wezterm)$",
    },
})

hl.bind(mainMod .. " + " .. "Return", hl.dsp.exec_cmd("handlr launch x-scheme-handler/terminal --"))

hl.bind(mainMod .. " + " .. "Q", hl.dsp.window.close())

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. "Q", hl.dsp.exec_cmd("wlogout"))

hl.bind(mainMod .. " + " .. "R", hl.dsp.exec_cmd("pkill fuzzel || fuzzel"))

hl.bind(mainMod .. " + " .. "W", hl.dsp.exec_cmd("wezterm"))

hl.bind(mainMod .. " + " .. 1, hl.dsp.focus({ workspace = 1 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 1, hl.dsp.window.move(1))

hl.bind(mainMod .. " + " .. 2, hl.dsp.focus({ workspace = 2 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 2, hl.dsp.window.move(2))

hl.bind(mainMod .. " + " .. 3, hl.dsp.focus({ workspace = 3 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 3, hl.dsp.window.move(3))

hl.bind(mainMod .. " + " .. 4, hl.dsp.focus({ workspace = 4 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 4, hl.dsp.window.move(4))

hl.bind(mainMod .. " + " .. 5, hl.dsp.focus({ workspace = 5 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 5, hl.dsp.window.move(5))

hl.bind(mainMod .. " + " .. 6, hl.dsp.focus({ workspace = 6 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 6, hl.dsp.window.move(6))

hl.bind(mainMod .. " + " .. 7, hl.dsp.focus({ workspace = 7 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 7, hl.dsp.window.move(7))

hl.bind(mainMod .. " + " .. 8, hl.dsp.focus({ workspace = 8 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 8, hl.dsp.window.move(8))

hl.bind(mainMod .. " + " .. 9, hl.dsp.focus({ workspace = 9 }))

hl.bind(mainMod .. " + " .. "SHIFT" .. " + " .. 9, hl.dsp.window.move(9))

hl.bind(mainMod .. " + " .. 0, hl.dsp.focus({ workspace = 10 }))




hl.monitor({
    output   = "desc:BOE 0x0C3F",
    mode     = "1920x1200",
    position = "0x0",
    scale    = 1,
})

hl.monitor({
    output   = "desc:Ancor Communications Inc ASUS PB278 E8LMTF000788",
    mode     = "2560x1440",
    position = "1920x0",
    scale    = 1,
})

hl.monitor({
    output   = "desc:Ancor Communications Inc ASUS PB278 E8LMTF000809",
    mode     = "2560x1440",
    position = "4480x0",
    scale    = 1,
})

hl.workspace_rule({
    workspace = 1,
    monitor = "desc:BOE 0x0C3F",
    is_default = true,
})

hl.workspace_rule({
    workspace = 2,
    monitor = "desc:Ancor Communications Inc ASUS PB278 E8LMTF000788",
    is_default = true,
})

hl.workspace_rule({
    workspace = 3,
    monitor = "desc:Ancor Communications Inc ASUS PB278 E8LMTF000809",
    is_default = true,
})

-- Autostart
hl.on("hyprland.start", function()
    hl.exec_cmd("/nix/store/5gln2rkcjx93cr5x0rr3wqrxjdmshd2f-dbus-1.16.2/bin/dbus-update-activation-environment --systemd DISPLAY HYPRLAND_INSTANCE_SIGNATURE WAYLAND_DISPLAY XDG_CURRENT_DESKTOP && systemctl --user stop hyprland-session.target && systemctl --user start hyprland-session.target")
    hl.exec_cmd("hyprpaper")
    hl.exec_cmd("hypridle")
    hl.exec_cmd("waybar")
end)
